spring.application.name=MySpringBootApp
# port \uBC88\uD638 \uBCC0\uACBD
#server.port=8085

# \uC0AC\uC6A9\uC790\uAC00 \uC815\uC758\uD55C \uD658\uACBD\uBCC0\uC218
myboot.age=${random.int(1,100)}
myboot.fullName=${myboot.name} Boot

# \uD604\uC7AC \uD65C\uC131\uD654\uB41C \uD658\uACBD\uC744 \uB098\uD0C0\uB0B4\uB294 \uBB38\uC790\uC5F4\uC124\uC815
spring.profiles.active=prod

# log file
logging.file.path=logs

# CORS \uD5C8\uC6A9 Origin ( \uC27C\uD45C\uB85C \uAD6C\uBD84, \uD504\uB860\uD2B8\uC5D4\uB4DC \uAC1C\uBC1C\uC11C\uBC84 \uC8FC\uC18C )
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173,http://127.0.0.1:5500